### ISSUE TITLE
Enabling SysMain in Windows 11

### ISSUE THREAD

**Issue by codefinecode** [OSPanel/SPTool#1]
You are not a good person.
firstly, the SSD under Windows does not defragment as you think. no need to optimize it. secondly, it breaks wsl - in addition to the fact that a lot of projects have disappeared, a lot of time has also been spent dealing with the problem.

```
Filename: "{sys}\sc.exe"; Parameters: "stop SysMain"; Flags: runascurrentuser runhidden waituntilterminated; Tasks: task_SSD
Filename: "{sys}\sc.exe"; Parameters: "config SysMain start= disabled"; Flags: runascurrentuser runhidden waituntilterminated; Tasks: task_SSD
```

These lines stop the SysMain (Superfetch) service and disable its autostart.
 
Those who, like me, regretted a thousand times that they accidentally left this checkbox (optimize Windows for SSD) - try restoring the parameters of the SysMain (Superfetch) service. This can be done by starting a command prompt with administrator rights and running the following commands:
 
```
sc config SysMain start= auto
sc start SysMain
```
 Restart your computer and try using WSL again.

**Comment by codefinecode** [comment]
also in Windows Features must be enabled:
Hyper-V
Virtual Machine Platform Windows
Subsystem Linux

after:
 1. Click Start and search "Exploit protection settings"
 2. Switch to "Program settings" tab along the top
 3. Add/Locate "C:\WINDOWS\System32\vmcompute.exe" in the list and expand it
 4. Click "Edit"
 5. Scroll down to "Code flow guard (CFG)" and uncheck/check "Override system settings" **(CFG must be ON for this app!)** 
 
 
 after that wsl Ubuntu worked for me

**Comment by OSPanel** [comment]
The SysMain service has nothing to do with SSD defragmentation and has no effect on WSL. WSL has nothing to do with the Open Server Panel program. Therefore, it is completely unclear what you are writing about.

However, thanks to your post, we found out that SysMain is also engaged in memory optimization in Windows 10/11 (an undocumented function), so we will move SysMain to the "Optimize Windows settings" section and turn it on instead of disabling it.

**Comment by codefinecode** [comment]
As your wish, but please test on win with wsl before merge master
